import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {mergeVertices} from 'three/addons/utils/BufferGeometryUtils.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {OutlinePass} from 'three/addons/postprocessing/OutlinePass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';

const MODEL_NAMES={mercedes:'Легковой автомобиль',mazda:'Кроссовер'};
const MODEL_URLS={mercedes:'models/mercedes.glb?v=5',mazda:'models/mazda.glb?v=5'};
function prefetchMazdaModel(){if(window.__mzPrefetch)return;window.__mzPrefetch=1;fetch(MODEL_URLS.mazda,{priority:'low'}).catch(()=>{})}
const DEFAULT_ZONE_DEFS={
 hood:['Капот',21600],roof:['Крыша',18500],bumperFront:['Бампер передний',18900],bumperRear:['Бампер задний',18900],
 fenderFrontR:['Крыло переднее левое',11200],fenderFrontL:['Крыло переднее правое',11200],doorFrontR:['Дверь передняя левая',13680],doorFrontL:['Дверь передняя правая',13680],doorRearR:['Дверь задняя левая',13680],doorRearL:['Дверь задняя правая',13680],
 quarterR:['Заднее крыло и стойка крыши левые',15400],quarterL:['Заднее крыло и стойка крыши правые',15400],sideLowerR:['Порог левый',9800],sideLowerL:['Порог правый',9800],mirrorR:['Зеркало левое',4200],mirrorL:['Зеркало правое',4200],
 headlights:['Фары передние',2000,{from:1,nopaint:1,note:'Полировка фар'}],taillights:['Фары задние',2000,{from:1,nopaint:1,note:'Полировка фар'}],
 windshield:['Полировка лобового',2000,{from:1,nopaint:1,note:'Полировка лобового'}],
 trunk:['Крышка багажника',14800],fuelCap:['Лючок бензобака',1000,{from:1,nopaint:1,note:'Оклейка лючка'}],handles:['Ручки дверей',2000,{from:1,nopaint:1,note:'Плёнка под ручки'}],pillars:['Стойки дверные',3000,{from:1,nopaint:1,note:'Оклейка стоек'}]
};
const STOCK_COLORS=[['#0b0d10','Obsidian Black'],['#f5f5f2','Pearl White'],['#d71935','Racing Red'],['#1246b8','Sapphire Blue'],['#0b6f46','Emerald Green'],['#bfc4cc','Silver'],['#d39b16','Champagne Gold'],['#6d2bbd','Electric Purple'],['#ff6b16','Burnt Orange'],['#e64f89','Candy Pink'],['#11a9b0','Turquoise'],['#63351f','Cocoa Brown']];
const STOCK_FINISHES=[{id:'gloss',name:'Глубокий глянец'},{id:'satin',name:'Сатин'},{id:'matte',name:'Матовая'}];
const STOCK_EFFECTS=[{id:'solid',name:'Solid'},{id:'metal',name:'Metallic'},{id:'pearl',name:'Pearl'}];
let wrapCfg=null,zoneDefs={...DEFAULT_ZONE_DEFS};
function zoneMapFrom(src){const next={};if(!src)return next;for(const id of Object.keys(DEFAULT_ZONE_DEFS)){const z=src[id];if(!z)continue;const opts={};if(z.from)opts.from=1;if(z.nopaint)opts.nopaint=1;if(z.note)opts.note=z.note;next[id]=Object.keys(opts).length?[z.name,+z.price||0,opts]:[z.name,+z.price||0]}return next}
function syncZoneDefs(model){const src=wrapCfg?.models?.[model]?.zones||wrapCfg?.zones;const next=zoneMapFrom(src);for(const id of Object.keys(DEFAULT_ZONE_DEFS))if(!next[id])next[id]=DEFAULT_ZONE_DEFS[id];zoneDefs=next}
function paletteColors(){const list=wrapCfg?.colors;if(!Array.isArray(list)||!list.length)return STOCK_COLORS.map(([hex,name])=>({hex,name,hidden:false}));return list.map((c,i)=>{const stock=STOCK_COLORS[i]||STOCK_COLORS[0];return {hex:String(c.hex||stock[0]),name:String(c.name||stock[1]),hidden:!!c.hidden}})}
function lookItems(kind){const stock=kind==='finish'?STOCK_FINISHES:STOCK_EFFECTS;const extra=wrapCfg?.[kind==='finish'?'finishes':'effects']||[];return stock.map(s=>{const o=extra.find(x=>x.id===s.id)||{};return {id:s.id,name:o.name||s.name,hidden:!!o.hidden}})}
function applyLookButtons(){lookItems('finish').forEach(item=>{document.querySelectorAll('[data-finish="'+item.id+'"]').forEach(b=>{b.textContent=item.name;b.hidden=!!item.hidden})});lookItems('effect').forEach(item=>{document.querySelectorAll('[data-effect="'+item.id+'"]').forEach(b=>{b.textContent=item.name;b.hidden=!!item.hidden})});const visF=lookItems('finish').find(x=>!x.hidden);if(visF&&lookItems('finish').find(x=>x.id===finish)?.hidden){finish=visF.id;document.querySelectorAll('[data-finish]').forEach(x=>x.classList.toggle('active',x.dataset.finish===finish))}const visE=lookItems('effect').find(x=>!x.hidden);if(visE&&lookItems('effect').find(x=>x.id===effect)?.hidden){effect=visE.id;document.querySelectorAll('[data-effect]').forEach(x=>x.classList.toggle('active',x.dataset.effect===effect))}}
function renderSwatches(){const box=document.getElementById('swatches');if(!box)return;box.innerHTML='';let list=paletteColors().filter(c=>!c.hidden);if(!list.length)list=paletteColors();if(!list.some(c=>c.hex.toLowerCase()===String(activeHex).toLowerCase())&&list[0])activeHex=list[0].hex;for(const c of list){const b=document.createElement('button');b.className='swatch'+(c.hex.toLowerCase()===String(activeHex).toLowerCase()?' active':'');b.style.background=c.hex;b.title=c.name+' '+c.hex;b.dataset.hex=c.hex;b.onclick=()=>{activeHex=c.hex;document.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('active',x===b));if(selectedZone){const old=tool;if(tool==='select')tool='fill';paintZone(selectedZone);tool=old}};box.appendChild(b)}}
function applyWrapZoneConfig(cfg){if(cfg&&typeof cfg==='object')wrapCfg=cfg;syncZoneDefs(activeModel||'mercedes');renderSwatches();applyLookButtons();if(roots[activeModel])rebuildZoneUI()}
async function loadWrapZoneConfig(){try{const r=await fetch('./data/wrap-zones.json?v='+Date.now());if(r.ok)applyWrapZoneConfig(await r.json())}catch(e){}}
const PRESETS={0:null,1:{hex:'#0b0d10',finish:'satin',effect:'pearl'},2:{hex:'#63351f',finish:'gloss',effect:'metal'},3:{hex:'#f5f5f2',finish:'gloss',effect:'metal'}};
// L/R zone ids follow model x<0 / x>0; with the car facing +z, x<0 is the car's right side.
const INFO_ANCHORS={
 mercedes:{handles:[[.872,.92,-.02],[.871,.925,-1.02],[-.872,.92,-.02],[-.871,.925,-1.02]],fuelCap:[[-.85,.9,-1.53]],pillars:[[.72,1.15,-.33],[-.72,1.15,-.33]]},
 mazda:{handles:[[.898,.99,-.12],[.882,1.06,-1.09],[-.898,.99,-.12],[-.882,1.06,-1.09]],fuelCap:[[.855,1.03,-1.66]],pillars:[[.714,1.35,-.33],[-.714,1.35,-.33]]}
};
const LIGHT_SOURCE={mercedes:'Object_4',mazda:'Object_8'};
const dodgeMap={
 hood:['BodyPanel_00_Front_R','BodyPanel_12_Front_R'],roof:['BodyPanel_07_Rear_L','BodyPanel_08_Rear_R','BodyPanel_11_Center_R','BodyPanel_27_Center_L','BodyPanel_28_Center_L','BodyPanel_29_Center_L','BodyPanel_31_Center_R','BodyPanel_32_Center_R','BodyPanel_33_Center_R','BodyPanel_43_Rear_R'],
 fenderFrontL:['BodyPanel_03_MidFront_L','BodyPanel_19_Front_L','BodyPanel_41_Front_L','BodyPanel_45_MidFront_L','BodyPanel_54_MidFront_L','BodyPanel_38_MidFront_L'],fenderFrontR:['BodyPanel_04_MidFront_R','BodyPanel_20_Front_R','BodyPanel_42_Front_R','BodyPanel_47_MidFront_R','BodyPanel_55_MidFront_R','BodyPanel_40_MidFront_R'],
 doorFrontL:['BodyPanel_09_Center_L','BodyPanel_14_Center_L','BodyPanel_30_Center_L','BodyPanel_44_Center_L','BodyPanel_49_Center_L','BodyPanel_50_Center_L'],doorFrontR:['BodyPanel_10_Center_R','BodyPanel_16_Center_R','BodyPanel_34_Center_R','BodyPanel_46_Center_R','BodyPanel_52_Center_R','BodyPanel_53_Center_R'],
 quarterL:['BodyPanel_05_Rear_L','BodyPanel_13_Rear_L','BodyPanel_22_Rear_L','BodyPanel_23_Back_L','BodyPanel_37_Back_L'],quarterR:['BodyPanel_06_Rear_R','BodyPanel_15_Rear_R','BodyPanel_24_Rear_R','BodyPanel_25_Back_R','BodyPanel_39_Back_R'],trunk:['BodyPanel_01_Back_R','BodyPanel_17_Back_L','BodyPanel_18_Back_R'],bumperFront:['BodyPanel_02_Front_R','BodyPanel_48_Front_L','BodyPanel_51_Front_R'],bumperRear:['BodyPanel_21_Back_R','BodyPanel_26_Back_L'],sideLowerL:['BodyPanel_35_Center_L'],sideLowerR:['BodyPanel_36_Center_R']
};
let activeModel='mercedes',tool='select',finish='gloss',effect='solid',activeHex='#d71935',selectedZone=null,total=0,rotating=true;
const states={mercedes:new Map(),mazda:new Map()}, zones={};
const app=document.getElementById('canvas'), scene=new THREE.Scene();
scene.background=new THREE.Color(0x080a0e);
const camera=new THREE.PerspectiveCamera(35,1,.01,100);camera.position.set(4.8,2.2,6.2);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.physicallyCorrectLights=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;app.appendChild(renderer.domElement);
const composer=new EffectComposer(renderer,new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,samples:4}));composer.addPass(new RenderPass(scene,camera));const outline=new OutlinePass(new THREE.Vector2(1,1),scene,camera);outline.visibleEdgeColor.set(0xff2a3c);outline.hiddenEdgeColor.set(0x3a0a12);outline.edgeStrength=5;outline.edgeThickness=1.4;outline.edgeGlow=.4;composer.addPass(outline);composer.addPass(new OutputPass());
const hlMat=new THREE.MeshBasicMaterial({color:0xff2a3c,transparent:true,opacity:.11,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2});const lightMat=hlMat.clone();lightMat.opacity=.04;let hlMeshes=[];
scene.add(new THREE.HemisphereLight(0xffffff,0x111522,2.2));
const key=new THREE.DirectionalLight(0xffffff,4.5);key.position.set(4,7,6);scene.add(key);const fill=new THREE.DirectionalLight(0x8bb8ff,1.8);fill.position.set(-5,3,-4);scene.add(fill);
let envReady=false;function ensureEnv(){if(envReady)return;envReady=true;const pmrem=new THREE.PMREMGenerator(renderer);const envScene=new RoomEnvironment();scene.environment=pmrem.fromScene(envScene,.04).texture;envScene.dispose();pmrem.dispose()}
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.rotateSpeed=.7;controls.target.set(0,.7,0);controls.minDistance=3.2;controls.maxDistance=11;
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();const loader=new GLTFLoader();const roots={};
function smoothMesh(mesh){if(!mesh.isMesh||!mesh.geometry||mesh.userData.part||mesh.userData.proxy)return;try{mesh.geometry=mergeVertices(mesh.geometry,1e-4)}catch(e){}mesh.geometry.computeVertexNormals();mesh.material.flatShading=false;mesh.material.needsUpdate=true;if('envMapIntensity' in mesh.material)mesh.material.envMapIntensity=1.35}
// Shared attributes would give every part the bounds of the whole source mesh.
function fitBounds(g){const pos=g.attributes.position,idx=g.index.array,b=new THREE.Box3(),v=new THREE.Vector3();for(let i=0;i<idx.length;i++)b.expandByPoint(v.fromBufferAttribute(pos,idx[i]));g.boundingBox=b;g.boundingSphere=b.getBoundingSphere(new THREE.Sphere())}
// Parts share the parent's vertex attributes, so shading across the cut stays seamless.
function splitMesh(mesh,root,classify){const g=mesh.geometry;if(!g.index||!mesh.parent)return;root.updateMatrixWorld(true);const rel=new THREE.Matrix4().copy(root.matrixWorld).invert().multiply(mesh.matrixWorld);const pos=g.attributes.position,idx=g.index.array;const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),cen=new THREE.Vector3(),n=new THREE.Vector3(),e=new THREE.Vector3();const buckets={};
for(let t=0;t<idx.length;t+=3){a.fromBufferAttribute(pos,idx[t]).applyMatrix4(rel);b.fromBufferAttribute(pos,idx[t+1]).applyMatrix4(rel);c.fromBufferAttribute(pos,idx[t+2]).applyMatrix4(rel);cen.copy(a).add(b).add(c).divideScalar(3);n.subVectors(b,a).cross(e.subVectors(c,a)).normalize();const z=classify(cen,n,t/3);if(z)(buckets[z]||=[]).push(idx[t],idx[t+1],idx[t+2])}
for(const [z,list] of Object.entries(buckets)){const pg=new THREE.BufferGeometry();for(const [k,v] of Object.entries(g.attributes))pg.setAttribute(k,v);pg.setIndex(list);fitBounds(pg);const pm=new THREE.Mesh(pg,mesh.material.clone());pm.name=mesh.name+'__'+z;pm.userData.part=z;pm.position.copy(mesh.position);pm.quaternion.copy(mesh.quaternion);pm.scale.copy(mesh.scale);mesh.parent.add(pm)}mesh.parent.remove(mesh)}
function meshTris(mesh,root){const g=mesh.geometry,pos=g.attributes.position,idx=g.index.array,T=idx.length/3;root.updateMatrixWorld(true);const rel=new THREE.Matrix4().copy(root.matrixWorld).invert().multiply(mesh.matrixWorld);const vk=new Map(),vid=new Int32Array(pos.count);
for(let i=0;i<pos.count;i++){const k=Math.round(pos.getX(i)*1e4)+','+Math.round(pos.getY(i)*1e4)+','+Math.round(pos.getZ(i)*1e4);if(!vk.has(k))vk.set(k,vk.size);vid[i]=vk.get(k)}
const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3();const nor=new Float32Array(T*3),cen=new Float32Array(T*3);
for(let t=0;t<T;t++){a.fromBufferAttribute(pos,idx[3*t]).applyMatrix4(rel);b.fromBufferAttribute(pos,idx[3*t+1]).applyMatrix4(rel);c.fromBufferAttribute(pos,idx[3*t+2]).applyMatrix4(rel);cen[3*t]=(a.x+b.x+c.x)/3;cen[3*t+1]=(a.y+b.y+c.y)/3;cen[3*t+2]=(a.z+b.z+c.z)/3;b.sub(a);c.sub(a);b.cross(c).normalize();nor[3*t]=b.x;nor[3*t+1]=b.y;nor[3*t+2]=b.z}
return {T,idx,vid,cen,nor}}
// Triangles passing mask, grouped into surfaces that do not cross creases sharper than deg.
function creaseRegions(m,mask,deg){const {T,idx,vid,nor,cen}=m;const edges=new Map();for(let t=0;t<T;t++){if(!mask(t))continue;for(let k=0;k<3;k++){const u=vid[idx[3*t+k]],v=vid[idx[3*t+(k+1)%3]];const key=u<v?u*1e7+v:v*1e7+u;const l=edges.get(key);if(l)l.push(t);else edges.set(key,[t])}}
const p=new Int32Array(T).map((_,i)=>i),f=x=>{while(p[x]!==x){p[x]=p[p[x]];x=p[x]}return x},cosMax=Math.cos(deg*Math.PI/180);
for(const l of edges.values())for(let i=1;i<l.length;i++){const x=l[0],y=l[i];if(Math.abs(nor[3*x]*nor[3*y]+nor[3*x+1]*nor[3*y+1]+nor[3*x+2]*nor[3*y+2])>=cosMax)p[f(x)]=f(y)}
const reg=new Int32Array(T).fill(-1),boxes=[],ids=new Map();for(let t=0;t<T;t++){if(!mask(t))continue;const r=f(t);if(!ids.has(r)){ids.set(r,boxes.length);boxes.push([9,9,9,-9,-9,-9])}const id=ids.get(r),s=boxes[id];reg[t]=id;for(let k=0;k<3;k++){s[k]=Math.min(s[k],cen[3*t+k]);s[k+3]=Math.max(s[k+3],cen[3*t+k])}}
return {reg,boxes}}
// Mercedes black roof lives in the shared body mesh; the sunroof glass and the side mouldings stay unpainted.
function splitMercedesRoof(root){const mesh=root.getObjectByName('Object_1');if(!mesh?.geometry?.index)return;const m=meshTris(mesh,root);const {reg,boxes}=creaseRegions(m,t=>m.cen[3*t+1]>1.3&&m.nor[3*t+1]>.3,20);
const keep=boxes.map(s=>{const hatch=s[3]-s[0]>.9&&s[2]>-.6&&s[5]<.08;return s[4]>=1.415&&Math.abs((s[0]+s[3])/2)<.3&&!hatch});splitMesh(mesh,root,(c,n,t)=>reg[t]>=0&&keep[reg[t]]?'roof':'body')}
// Mercedes mirror caps are islands of the remaining body mesh; the glass and the turn-signal strip are thin islands and stay out.
function splitMercedesMirrors(root){const mesh=root.getObjectByName('Object_1__body');if(!mesh?.geometry?.index)return;const {T,idx,vid,cen}=meshTris(mesh,root);let nv=0;for(const v of vid)if(v>=nv)nv=v+1;const p=new Int32Array(nv).map((_,i)=>i),f=x=>{while(p[x]!==x){p[x]=p[p[x]];x=p[x]}return x};for(let t=0;t<T;t++){const r=f(vid[idx[3*t]]);p[f(vid[idx[3*t+1]])]=r;p[f(vid[idx[3*t+2]])]=r}
const isl=new Map(),of=new Int32Array(T);for(let t=0;t<T;t++){const r=f(vid[idx[3*t]]);let s=isl.get(r);if(!s)isl.set(r,s={n:0,b:[9,9,9,-9,-9,-9],zone:null});s.n++;of[t]=r;for(let k=0;k<3;k++){s.b[k]=Math.min(s.b[k],cen[3*t+k]);s.b[k+3]=Math.max(s.b[k+3],cen[3*t+k])}}
let found=false;for(const s of isl.values()){const b=s.b,cx=(b[0]+b[3])/2,cy=(b[1]+b[4])/2,cz=(b[2]+b[5])/2;if(s.n>=300&&Math.abs(cx)>.7&&cy>.9&&cy<1.2&&cz>.4&&cz<.85&&b[5]-b[2]<.5){s.zone=cx<0?'mirrorL':'mirrorR';found=true}}
if(found)splitMesh(mesh,root,(c,n,t)=>isl.get(of[t]).zone||'body')}
// Mazda paint is one mesh of 28 islands; ids follow triangle order of the source GLB.
const MAZDA_ISLANDS={25:'roof',5:'roof',3:'trunk',4:'trunk',7:'trunk',14:'trunk',8:'bumperRear',1:'bumperRear',2:'bumperRear',10:'bumperFront',6:'bumperFront',11:'doorFrontL',21:'doorFrontL',22:'doorFrontL',23:'doorFrontR',16:'doorFrontR',17:'doorFrontR',13:'doorRearL',24:'doorRearL',27:'doorRearL',26:'doorRearR',19:'doorRearR',20:'doorRearR',15:'mirrorL',18:'mirrorR'};
function splitMazdaBody(mesh,root){const g=mesh.geometry;if(!g.index)return;const pos=g.attributes.position,idx=g.index.array,T=idx.length/3;const vk=new Map(),vid=new Int32Array(pos.count);
for(let i=0;i<pos.count;i++){const k=Math.round(pos.getX(i)*1e4)+','+Math.round(pos.getY(i)*1e4)+','+Math.round(pos.getZ(i)*1e4);if(!vk.has(k))vk.set(k,vk.size);vid[i]=vk.get(k)}
const uf=n=>{const p=new Int32Array(n).map((_,i)=>i);const f=x=>{while(p[x]!==x){p[x]=p[p[x]];x=p[x]}return x};return [p,f]};
const [p1,f1]=uf(vk.size);for(let t=0;t<T;t++){const r=f1(vid[idx[3*t]]);p1[f1(vid[idx[3*t+1]])]=r;p1[f1(vid[idx[3*t+2]])]=r}
const island=new Int32Array(T),ids=new Map();for(let t=0;t<T;t++){const r=f1(vid[idx[3*t]]);if(!ids.has(r))ids.set(r,ids.size);island[t]=ids.get(r)}
if(ids.size!==28){splitMesh(mesh,root,()=>'hood');return}
root.updateMatrixWorld(true);const rel=new THREE.Matrix4().copy(root.matrixWorld).invert().multiply(mesh.matrixWorld);const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),e=new THREE.Vector3();const nor=new Float32Array(T*3),cen=new Float32Array(T*3);
for(let t=0;t<T;t++){a.fromBufferAttribute(pos,idx[3*t]).applyMatrix4(rel);b.fromBufferAttribute(pos,idx[3*t+1]).applyMatrix4(rel);c.fromBufferAttribute(pos,idx[3*t+2]).applyMatrix4(rel);cen[3*t]=(a.x+b.x+c.x)/3;cen[3*t+1]=(a.y+b.y+c.y)/3;cen[3*t+2]=(a.z+b.z+c.z)/3;b.sub(a);c.sub(a);e.crossVectors(b,c).normalize();nor[3*t]=e.x;nor[3*t+1]=e.y;nor[3*t+2]=e.z}
const edges=new Map();for(let t=0;t<T;t++){if(island[t]!==0)continue;for(let k=0;k<3;k++){const u=vid[idx[3*t+k]],v=vid[idx[3*t+(k+1)%3]];const key=u<v?u*1e7+v:v*1e7+u;const l=edges.get(key);if(l)l.push(t);else edges.set(key,[t])}}
const [p2,f2]=uf(T),cosMax=Math.cos(25*Math.PI/180);for(const l of edges.values()){if(l.length!==2)continue;const [p,q]=l;if(Math.abs(nor[3*p]*nor[3*q]+nor[3*p+1]*nor[3*q+1]+nor[3*p+2]*nor[3*q+2])>=cosMax)p2[f2(p)]=f2(q)}
const box=new Map();for(let t=0;t<T;t++){if(island[t]!==0)continue;const r=f2(t);let s=box.get(r);if(!s)box.set(r,s=[9,9,9,-9,-9,-9]);for(let k=0;k<3;k++){s[k]=Math.min(s[k],cen[3*t+k]);s[k+3]=Math.max(s[k+3],cen[3*t+k])}}
const frontZone=new Map();for(const [r,s] of box){const cx=(s[0]+s[3])/2,cy=(s[1]+s[4])/2,cz=(s[2]+s[5])/2;frontZone.set(r,cz>1.6&&cy<.87?'bumperFront':Math.abs(cx)<.74&&cy>.87?'hood':Math.abs(cx)>=.6?(cx<0?'fenderFrontL':'fenderFrontR'):'bumperFront')}
splitMesh(mesh,root,(c,n,t)=>{const i=island[t];if(i===0)return frontZone.get(f2(t));if(i===9||i===12)return c.x<0?'quarterL':'quarterR';return MAZDA_ISLANDS[i]})}
// Lamp lenses and the windshield are islands of the shared glass mesh; hidden proxies over them serve picking and the outline only.
function buildLights(root,model){if(root.userData.lights)return root.userData.lights;const out=root.userData.lights={headlights:[],taillights:[],windshield:[]};const src=root.getObjectByName(LIGHT_SOURCE[model]);if(!src?.geometry?.index||!src.parent)return out;const {T,idx,vid,cen}=meshTris(src,root);
let nv=0;for(const v of vid)if(v>=nv)nv=v+1;const p=new Int32Array(nv).map((_,i)=>i),f=x=>{while(p[x]!==x){p[x]=p[p[x]];x=p[x]}return x};for(let t=0;t<T;t++){const r=f(vid[idx[3*t]]);p[f(vid[idx[3*t+1]])]=r;p[f(vid[idx[3*t+2]])]=r}
const isl=new Map();for(let t=0;t<T;t++){const r=f(vid[idx[3*t]]);let s=isl.get(r);if(!s)isl.set(r,s={n:0,x:0,y:0,z:0,b:[9,9,-9,-9],tris:[]});s.n++;s.x+=cen[3*t];s.y+=cen[3*t+1];s.z+=cen[3*t+2];s.b[0]=Math.min(s.b[0],cen[3*t]);s.b[1]=Math.min(s.b[1],cen[3*t+2]);s.b[2]=Math.max(s.b[2],cen[3*t]);s.b[3]=Math.max(s.b[3],cen[3*t+2]);s.tris.push(t)}
const buckets={headlights:[],taillights:[],windshield:[]};for(const s of isl.values()){const cx=s.x/s.n,cy=s.y/s.n,cz=s.z/s.n;if(s.n<200)continue;const z=s.b[2]-s.b[0]>1.2&&s.b[3]-s.b[1]>.4&&cz>0&&cy>1?'windshield':s.n<300||Math.abs(cx)<.3||cy>1.25?null:cz>1.6?'headlights':cz<-1.6?'taillights':null;if(z)for(const t of s.tris)buckets[z].push(idx[3*t],idx[3*t+1],idx[3*t+2])}
for(const [z,list] of Object.entries(buckets)){if(!list.length)continue;const g=new THREE.BufferGeometry();for(const [k,v] of Object.entries(src.geometry.attributes))g.setAttribute(k,v);g.setIndex(list);fitBounds(g);const pm=new THREE.Mesh(g,lightMat);pm.name=src.name+'__'+z;pm.userData.proxy=true;pm.visible=false;pm.renderOrder=2;pm.position.copy(src.position);pm.quaternion.copy(src.quaternion);pm.scale.copy(src.scale);src.parent.add(pm);out[z].push(pm)}
return out}
function originalMaterial(mesh){const map=states[activeModel];let s=map.get(mesh.uuid);if(!s){s={original:mesh.material.clone?mesh.material.clone():mesh.material,hex:null};map.set(mesh.uuid,s)}return s}
function applyMaterial(mesh,hex){const s=originalMaterial(mesh);const m=new THREE.MeshPhysicalMaterial({color:new THREE.Color(hex),roughness:.15,metalness:.05,envMapIntensity:1.5,clearcoat:.0,clearcoatRoughness:.12});
if(finish==='gloss'){m.roughness=.07;m.clearcoat=.42;m.clearcoatRoughness=.07}
if(finish==='satin'){m.roughness=.34;m.clearcoat=.12;m.clearcoatRoughness=.22}
if(finish==='matte'){m.roughness=.88;m.clearcoat=0}
if(effect==='metal'){m.metalness=.9;m.roughness=finish==='matte'?.58:finish==='satin'?.28:.17}
if(effect==='pearl'){m.metalness=.18;m.roughness=finish==='matte'?.68:finish==='satin'?.3:.12;m.iridescence=.28;m.iridescenceIOR=1.45;m.iridescenceThicknessRange=[120,420]}
mesh.material=m;s.hex=hex;s.finish=finish;s.effect=effect}
function resetZone(id){for(const mesh of zones[id]||[]){const s=states[activeModel].get(mesh.uuid);if(!s)continue;if(s.original)mesh.material=s.original.clone?s.original.clone():s.original;s.hex=null}}
function paintZone(id){if(!id||zoneDefs[id]?.[2]?.nopaint)return;if(tool==='remove')resetZone(id);else if(tool==='eyedrop'){const s=(zones[id]||[]).map(m=>states[activeModel].get(m.uuid)).find(x=>x?.hex);if(s){activeHex=s.hex;document.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('active',x.dataset.hex===activeHex))}}else if(tool!=='select'){for(const mesh of zones[id]||[])applyMaterial(mesh,activeHex)}recalc();renderParts()}
function friendly(id){return zoneDefs[id]?.[0]||id}function price(id){return zoneDefs[id]?.[1]||0}
function priceText(id){return (zoneDefs[id]?.[2]?.from?'от ':'')+price(id).toLocaleString('ru-RU')+' ₽'}
function subText(id){const note=zoneDefs[id]?.[2]?.note;return note?note+' · '+MODEL_NAMES[activeModel]:MODEL_NAMES[activeModel]}
function infoAnchors(id){return INFO_ANCHORS[activeModel]?.[id]}
const pins=[];function hidePins(from=0){for(let i=from;i<pins.length;i++)pins[i].style.display='none'}
function clearHighlight(){hlMeshes.forEach(h=>h.userData.proxy?h.visible=false:h.removeFromParent());hlMeshes=[];outline.selectedObjects=[];hidePins()}
function selectZone(id){clearHighlight();selectedZone=id;const ms=zones[id]||[];for(const m of ms){if(m.userData.proxy){m.visible=true;hlMeshes.push(m);continue}const h=new THREE.Mesh(m.geometry,hlMat);h.raycast=()=>{};h.renderOrder=2;m.add(h);hlMeshes.push(h)}outline.selectedObjects=ms;document.getElementById('selectedInfo').innerHTML=`<b>${friendly(id)}</b><br>Стоимость: ${priceText(id)}<br><span style="color:#777d88">${subText(id)}</span>`;document.getElementById('status').textContent=friendly(id);markerFor(id);renderParts()}
function markerFor(id){const marker=document.getElementById('marker');const anchors=infoAnchors(id);if(!id||(!(zones[id]||[]).length&&!anchors)){marker.style.display='none';hidePins();return}const r=app.getBoundingClientRect();const px=v=>[(v.x*.5+.5)*r.width,(-v.y*.5+.5)*r.height];let x,y;
if(anchors){const root=roots[activeModel];root.updateMatrixWorld();const pts=anchors.map(a=>{const w=root.localToWorld(new THREE.Vector3(...a));const n=new THREE.Vector3(Math.sign(a[0]),0,0).applyQuaternion(root.quaternion);return {s:px(w.clone().project(camera)),vis:n.dot(camera.position.clone().sub(w))>0}});const vis=pts.filter(p=>p.vis),use=vis.length?vis:pts;
vis.forEach((p,i)=>{let el=pins[i];if(!el){el=document.createElement('div');el.className='pin';marker.parentElement.appendChild(el);pins[i]=el}el.style.left=p.s[0]+'px';el.style.top=p.s[1]+'px';el.style.display='block'});hidePins(vis.length);
x=use.reduce((a,p)=>a+p.s[0],0)/use.length;y=Math.min(...use.map(p=>p.s[1]))-(vis.length?34:0)}
else{const box=new THREE.Box3();zones[id].forEach(m=>box.expandByObject(m));[x,y]=px(box.getCenter(new THREE.Vector3()).project(camera))}
marker.style.left=x+'px';marker.style.top=y+'px';marker.innerHTML=`<strong>${friendly(id)}</strong><small>${subText(id)}</small><b>${priceText(id)}</b>`;marker.style.display='block'}
const UP=new THREE.Vector3(0,1,0);let turn=null;
function yawOf(o){return 2*Math.atan2(o.quaternion.y,o.quaternion.w)}
function faceZone(id){const root=roots[activeModel];if(!root)return;root.updateMatrixWorld(true);let dirs;const anchors=infoAnchors(id);
if(anchors)dirs=anchors.map(a=>[a[0],a[2]]);else{const box=new THREE.Box3();(zones[id]||[]).forEach(m=>box.expandByObject(m));if(box.isEmpty())return;const c=root.worldToLocal(box.getCenter(new THREE.Vector3()));if(Math.hypot(c.x,c.z)<.35)return;dirs=[[c.x,c.z]]}
const t=controls.target,view=Math.atan2(camera.position.x-t.x,camera.position.z-t.z),cur=yawOf(root);let best=null;
for(const [x,z] of dirs){let d=view-Math.atan2(x,z)-cur;d=Math.atan2(Math.sin(d),Math.cos(d));if(best===null||Math.abs(d)<Math.abs(best))best=d}
rotating=false;document.getElementById('rotate').classList.remove('active');if(Math.abs(best)<50*Math.PI/180)return;turn={root,from:cur,to:cur+best,t0:performance.now()}}
function stepTurn(now){if(!turn)return;const k=Math.min(1,(now-turn.t0)/1071),e=1-Math.pow(1-k,3);turn.root.quaternion.setFromAxisAngle(UP,turn.from+(turn.to-turn.from)*e);if(k>=1)turn=null}
function recalc(){total=0;for(const [id,ms] of Object.entries(zones))if(ms.some(m=>states[activeModel].get(m.uuid)?.hex))total+=price(id);document.getElementById('total').textContent=total.toLocaleString('ru-RU')+' ₽'}
function renderParts(){const box=document.getElementById('parts');if(!box)return;box.innerHTML='';const painted=Object.keys(zoneDefs).filter(id=>(zones[id]||[]).some(m=>states[activeModel].get(m.uuid)?.hex));if(!painted.length){box.innerHTML='<div class="empty">Пока ничего не выбрано</div>';return}painted.forEach(id=>{const b=document.createElement('button');b.className='part'+(selectedZone===id?' active':'');b.innerHTML=`<span><span class="name">${friendly(id)}</span><span class="meta">${MODEL_NAMES[activeModel]}</span></span><span class="price">${priceText(id)}</span>`;b.onclick=()=>{selectZone(id);faceZone(id)};box.appendChild(b)})}
function setLook(hex,fin,eff){if(hex){activeHex=hex;document.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('active',x.dataset.hex===hex))}if(fin){finish=fin;document.querySelectorAll('[data-finish]').forEach(x=>x.classList.toggle('active',x.dataset.finish===fin))}if(eff){effect=eff;document.querySelectorAll('[data-effect]').forEach(x=>x.classList.toggle('active',x.dataset.effect===eff))}}
const PRESET_STOCK={mercedes:new Set(['roof','mirrorL','mirrorR'])};
function wrapCar(p){if(!p){for(const id of Object.keys(zoneDefs))resetZone(id)}else{setLook(p.hex,p.finish,p.effect);const keep=PRESET_STOCK[activeModel];for(const id of Object.keys(zoneDefs)){if(zoneDefs[id][2]?.nopaint)continue;if(keep?.has(id)){resetZone(id);continue}for(const mesh of zones[id]||[])applyMaterial(mesh,p.hex)}}recalc();renderParts()}
function currentPreset(){const a=document.querySelector('[data-preset].active');return PRESETS[a?+a.dataset.preset:0]}
function applyPreset(n){document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===String(n)));wrapCar(PRESETS[n])}
function rebuildZoneUI(){const box=document.getElementById('zones');box.innerHTML='';for(const id of Object.keys(zoneDefs)){if(!(zones[id]||[]).length&&!infoAnchors(id))continue;const b=document.createElement('button');b.className='zone';b.innerHTML=`${friendly(id)}<small>${priceText(id)}</small>`;b.onclick=()=>{selectZone(id);faceZone(id);if(tool!=='select')paintZone(id)};box.appendChild(b)} }
function buildZones(root,model){Object.keys(zones).forEach(k=>delete zones[k]);const map=new Map();root.traverse(o=>{if(o.isMesh){smoothMesh(o);map.set(o.name,o)}});if(model==='mazda'){for(const id of Object.keys(zoneDefs))zones[id]=[];const body=root.getObjectByName('Object_12');if(body)splitMazdaBody(body,root);root.traverse(o=>{if(o.isMesh&&o.userData.part)zones[o.userData.part]?.push(o)})}else{for(const id of Object.keys(zoneDefs))zones[id]=[];splitMercedesRoof(root);splitMercedesMirrors(root);const frontDoorL=/^MBPanel_(030|031|034)_/;const frontDoorR=/^MBPanel_(037|038|041)_/;const rearDoorL=/^MBPanel_(032|036|076|077|079|080|081|083|095|096|097|098|099|100|101)_/;const rearDoorR=/^MBPanel_(039|043|113|114|115|116|117|118|119|120|121|123|124|125|127)_/;root.traverse(o=>{if(!o.isMesh)return;let zone=null;if(o.userData.part)zone=o.userData.part;else if(o.name==='MBPanel_010_trunk'||o.name==='MBPanel_011_roof')zone='quarterL';else if(o.name==='MBPanel_018_roof')zone='quarterR';else if(o.name==='MBPanel_203_quarterL'||o.name==='MBPanel_213_quarterR')zone='bumperRear';else if(o.name==='MBPanel_141_mirrorL')zone='doorFrontL';else if(o.name==='MBPanel_150_mirrorR')zone='doorFrontR';else if(o.name==='MBPanel_017_trunk')zone='quarterR';else if(rearDoorL.test(o.name))zone='doorRearL';else if(rearDoorR.test(o.name))zone='doorRearR';else if(frontDoorL.test(o.name))zone='doorFrontL';else if(frontDoorR.test(o.name))zone='doorFrontR';else{const m=o.name.match(/_((?:hood|roof|fenderFrontL|fenderFrontR|doorFrontL|doorFrontR|doorRearL|doorRearR|quarterL|quarterR|trunk|bumperFront|bumperRear|sideLowerL|sideLowerR|mirrorL|mirrorR))$/);if(m)zone=m[1]}if(zone)zones[zone]?.push(o)})}const lights=buildLights(root,model);zones.headlights=lights.headlights;zones.taillights=lights.taillights;zones.windshield=lights.windshield;rebuildZoneUI();selectedZone=null;document.getElementById('selectedInfo').textContent='Нажмите на деталь автомобиля';wrapCar(currentPreset())}
function coverMercedesPlate(root){root.traverse(o=>{if(!o.isMesh)return;if(o.name!=='Object_6'&&o.material?.name!=='metal_white')return;o.material=new THREE.MeshPhysicalMaterial({color:0x111111,roughness:.45,metalness:.15,envMapIntensity:.6})})}
function onModelReady(model,r){if(roots[model])return;ensureEnv();r.scale.setScalar(model==='mazda'?1.38:1.45);r.position.y=.03;scene.add(r);roots[model]=r;Object.values(roots).forEach(x=>x.visible=false);r.visible=true;try{buildZones(r,model);if(model==='mercedes')coverMercedesPlate(r);else{const plate=r.getObjectByName('Object_13');if(plate)plate.visible=false}}catch(e){console.warn(e)}document.getElementById('status').textContent=MODEL_NAMES[model]+' готов'}
function loadModel(model){turn=null;clearHighlight();selectedZone=null;document.getElementById('marker').style.display='none';activeModel=model;syncZoneDefs(model);document.querySelectorAll('[data-model]').forEach(b=>b.classList.toggle('active',b.dataset.model===model));if(roots[model]){Object.values(roots).forEach(r=>r.visible=false);roots[model].visible=true;controls.target.set(0,.7,0);selectedZone=null;buildZones(roots[model],model);if(model==='mercedes')coverMercedesPlate(roots[model]);document.getElementById('status').textContent=MODEL_NAMES[model]+' готов';return}document.getElementById('status').textContent='Загрузка '+MODEL_NAMES[model];let settled=false;const ok=g=>{if(settled||roots[model])return;settled=true;onModelReady(model,g.scene)};const fail=()=>{if(settled||roots[model])return;document.getElementById('status').textContent='Ошибка загрузки '+MODEL_NAMES[model]};const prog=xhr=>{if(settled||roots[model]||!xhr.total)return;document.getElementById('status').textContent='Загрузка '+MODEL_NAMES[model]+' '+Math.round(xhr.loaded/xhr.total*100)+'%'};const cached=window.__wrapGlb?.[model];if(cached){loader.parse(cached,'',ok,fail);return}loader.load(MODEL_URLS[model],ok,prog,fail)}
renderSwatches();
document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{if(b.dataset.model==='mazda')prefetchMazdaModel();loadModel(b.dataset.model)});
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(+b.dataset.preset));
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b))});
document.querySelectorAll('[data-finish]').forEach(b=>b.onclick=()=>{finish=b.dataset.finish;document.querySelectorAll('[data-finish]').forEach(x=>x.classList.toggle('active',x===b));if(selectedZone){const old=tool;if(tool==='select')tool='fill';paintZone(selectedZone);tool=old}});
document.querySelectorAll('[data-effect]').forEach(b=>b.onclick=()=>{effect=b.dataset.effect;document.querySelectorAll('[data-effect]').forEach(x=>x.classList.toggle('active',x===b));if(selectedZone){const old=tool;if(tool==='select')tool='fill';paintZone(selectedZone);tool=old}});
renderer.domElement.addEventListener('pointerdown',e=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const all=Object.values(zones).flat().filter(Boolean);const hits=ray.intersectObjects(all,true);if(!hits.length)return;let hit=hits[0].object,found=null;for(const [id,ms] of Object.entries(zones))if(ms.includes(hit)){found=id;break}if(found){rotating=false;document.getElementById('rotate').classList.remove('active');selectZone(found);if(tool!=='select')paintZone(found)}});
document.getElementById('rotate').onclick=()=>{rotating=!rotating;document.getElementById('rotate').classList.toggle('active',rotating)};
document.getElementById('reset').onclick=()=>{turn=null;camera.position.set(4.8,2.2,6.2);controls.target.set(0,.7,0);controls.update();if(roots[activeModel])roots[activeModel].rotation.set(0,0,0)};
document.getElementById('quote').onclick=()=>alert(`Подбор сформирован для ${MODEL_NAMES[activeModel]}. Здесь можно подключить CRM/Telegram/форму заявки.`);
function resize(){const r=app.getBoundingClientRect();renderer.setSize(r.width,r.height,false);composer.setPixelRatio(renderer.getPixelRatio());composer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function loop(now){requestAnimationFrame(loop);stepTurn(now);if(rotating&&!turn&&roots[activeModel])roots[activeModel].rotateY(.00126);controls.update();if(outline.selectedObjects.length)composer.render();else renderer.render(scene,camera);if(selectedZone)markerFor(selectedZone)}loop();
loadWrapZoneConfig().finally(()=>{MeshoptDecoder.ready.then(()=>{loader.setMeshoptDecoder(MeshoptDecoder);loadModel('mercedes')})});
