
const MODEL_NAMES={dodge:'Dodge Challenger SRT Demon',mercedes:'Mercedes-Benz C-Class'};
const MODEL_URLS={dodge:'models/dodge.glb?v=3',mercedes:'models/mercedes.glb?v=3'};
function prefetchMercedesModel(){if(window.__mbPrefetch)return;window.__mbPrefetch=1;fetch(MODEL_URLS.mercedes,{priority:'low'}).catch(()=>{})}
const zoneDefs={
 hood:['Капот',21600],roof:['Крыша',18500],fenderFrontL:['Переднее крыло L',11200],fenderFrontR:['Переднее крыло R',11200],doorFrontL:['Передняя дверь L',13680],doorFrontR:['Передняя дверь R',13680],doorRearL:['Задняя дверь L',13680],doorRearR:['Задняя дверь R',13680],quarterL:['Задняя часть L',15400],quarterR:['Задняя часть R',15400],trunk:['Крышка багажника',14800],bumperFront:['Передний бампер',18900],bumperRear:['Задний бампер',18900],sideLowerL:['Нижняя часть L',9800],sideLowerR:['Нижняя часть R',9800],mirrorL:['Зеркало L',4200],mirrorR:['Зеркало R',4200]
};
const dodgeMap={
 hood:['BodyPanel_00_Front_R','BodyPanel_12_Front_R'],roof:['BodyPanel_07_Rear_L','BodyPanel_08_Rear_R','BodyPanel_11_Center_R','BodyPanel_27_Center_L','BodyPanel_28_Center_L','BodyPanel_29_Center_L','BodyPanel_31_Center_R','BodyPanel_32_Center_R','BodyPanel_33_Center_R','BodyPanel_43_Rear_R'],
 fenderFrontL:['BodyPanel_03_MidFront_L','BodyPanel_19_Front_L','BodyPanel_41_Front_L','BodyPanel_45_MidFront_L','BodyPanel_54_MidFront_L','BodyPanel_38_MidFront_L'],fenderFrontR:['BodyPanel_04_MidFront_R','BodyPanel_20_Front_R','BodyPanel_42_Front_R','BodyPanel_47_MidFront_R','BodyPanel_55_MidFront_R','BodyPanel_40_MidFront_R'],
 doorFrontL:['BodyPanel_09_Center_L','BodyPanel_14_Center_L','BodyPanel_30_Center_L','BodyPanel_44_Center_L','BodyPanel_49_Center_L','BodyPanel_50_Center_L'],doorFrontR:['BodyPanel_10_Center_R','BodyPanel_16_Center_R','BodyPanel_34_Center_R','BodyPanel_46_Center_R','BodyPanel_52_Center_R','BodyPanel_53_Center_R'],
 quarterL:['BodyPanel_05_Rear_L','BodyPanel_13_Rear_L','BodyPanel_22_Rear_L','BodyPanel_23_Back_L','BodyPanel_37_Back_L'],quarterR:['BodyPanel_06_Rear_R','BodyPanel_15_Rear_R','BodyPanel_24_Rear_R','BodyPanel_25_Back_R','BodyPanel_39_Back_R'],trunk:['BodyPanel_01_Back_R','BodyPanel_17_Back_L','BodyPanel_18_Back_R'],bumperFront:['BodyPanel_02_Front_R','BodyPanel_48_Front_L','BodyPanel_51_Front_R'],bumperRear:['BodyPanel_21_Back_R','BodyPanel_26_Back_L'],sideLowerL:['BodyPanel_35_Center_L'],sideLowerR:['BodyPanel_36_Center_R']
};
const colors=[['#0b0d10','Obsidian Black'],['#f5f5f2','Pearl White'],['#d71935','Racing Red'],['#1246b8','Sapphire Blue'],['#0b6f46','Emerald Green'],['#bfc4cc','Silver'],['#d39b16','Champagne Gold'],['#6d2bbd','Electric Purple'],['#ff6b16','Burnt Orange'],['#e64f89','Candy Pink'],['#11a9b0','Turquoise'],['#63351f','Cocoa Brown']];
let activeModel='dodge',tool='select',finish='gloss',effect='solid',activeHex='#d71935',selectedZone=null,total=0,rotating=true;
const states={dodge:new Map(),mercedes:new Map()}, zones={};
const app=document.getElementById('canvas'), scene=new THREE.Scene();
scene.background=new THREE.Color(0x080a0e);
const camera=new THREE.PerspectiveCamera(35,1,.01,100);camera.position.set(4.8,2.2,6.2);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;app.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x111522,2.2));
const key=new THREE.DirectionalLight(0xffffff,4.5);key.position.set(4,7,6);scene.add(key);const fill=new THREE.DirectionalLight(0x8bb8ff,1.8);fill.position.set(-5,3,-4);scene.add(fill);
let envReady=false;function ensureEnv(){if(envReady)return;envReady=true;const pmrem=new THREE.PMREMGenerator(renderer);const envScene=new RoomEnvironment();scene.environment=pmrem.fromScene(envScene,.04).texture;envScene.dispose();pmrem.dispose()}
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.target.set(0,.7,0);controls.minDistance=3.2;controls.maxDistance=11;
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();const loader=new GLTFLoader();const roots={};
function smoothMesh(mesh){if(!mesh.isMesh||!mesh.geometry)return;if(!mesh.geometry.attributes.normal)mesh.geometry.computeVertexNormals();mesh.material.flatShading=false;mesh.material.needsUpdate=true;if('envMapIntensity' in mesh.material)mesh.material.envMapIntensity=1.35}
function makeCanvasTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='#16191d';x.fillRect(0,0,128,128);x.strokeStyle='rgba(255,255,255,.12)';x.lineWidth=2;for(let i=-128;i<256;i+=18){x.beginPath();x.moveTo(i,0);x.lineTo(i+128,128);x.stroke();x.beginPath();x.moveTo(i,128);x.lineTo(i+128,0);x.stroke()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2.5,2.5);return t}
const carbonTex=makeCanvasTexture();
function originalMaterial(mesh){const map=states[activeModel];let s=map.get(mesh.uuid);if(!s){s={original:mesh.material.clone?mesh.material.clone():mesh.material,hex:null};map.set(mesh.uuid,s)}return s}
function applyMaterial(mesh,hex){const s=originalMaterial(mesh);const m=new THREE.MeshPhysicalMaterial({color:new THREE.Color(hex),roughness:.15,metalness:.05,envMapIntensity:1.5,clearcoat:.0,clearcoatRoughness:.12});
if(finish==='gloss'){m.roughness=.07;m.clearcoat=.42;m.clearcoatRoughness=.07}
if(finish==='satin'){m.roughness=.34;m.clearcoat=.12;m.clearcoatRoughness=.22}
if(finish==='matte'){m.roughness=.88;m.clearcoat=0}
if(effect==='metal'){m.metalness=.9;m.roughness=finish==='matte'?.58:finish==='satin'?.28:.17}
if(effect==='pearl'){m.metalness=.18;m.roughness=finish==='matte'?.68:finish==='satin'?.3:.12;m.iridescence=.28;m.iridescenceIOR=1.45;m.iridescenceThicknessRange=[120,420]}
if(effect==='carbon'){m.color=new THREE.Color(hex).multiplyScalar(.72);m.map=carbonTex;m.roughness=Math.max(.32,finish==='matte'?.8:finish==='satin'?.48:.28);m.metalness=.18}
mesh.material=m;s.hex=hex;s.finish=finish;s.effect=effect}
function resetZone(id){for(const mesh of zones[id]||[]){const s=states[activeModel].get(mesh.uuid);if(s?.original)mesh.material=s.original.clone?s.original.clone():s.original;s.hex=null}}
function paintZone(id){if(!id)return;if(tool==='remove')resetZone(id);else if(tool==='eyedrop'){const s=(zones[id]||[]).map(m=>states[activeModel].get(m.uuid)).find(x=>x?.hex);if(s){activeHex=s.hex;document.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('active',x.dataset.hex===activeHex))}}else if(tool!=='select'){for(const mesh of zones[id]||[])applyMaterial(mesh,activeHex)}recalc();renderParts()}
function friendly(id){return zoneDefs[id]?.[0]||id}function price(id){return zoneDefs[id]?.[1]||0}
function clearHighlight(){Object.values(zones).flat().forEach(m=>{if(m.material?.emissive)m.material.emissive.set(0);if(m.material)m.material.emissiveIntensity=0})}
function selectZone(id){clearHighlight();selectedZone=id;for(const m of zones[id]||[]){if(m.material?.emissive){m.material.emissive.set(0x5a1020);m.material.emissiveIntensity=.28}};document.getElementById('selectedInfo').innerHTML=`<b>${friendly(id)}</b><br>Стоимость: ${price(id).toLocaleString('ru-RU')} ₽<br><span style="color:#777d88">${MODEL_NAMES[activeModel]}</span>`;document.getElementById('status').textContent=friendly(id);markerFor(id);renderParts()}
function markerFor(id){const marker=document.getElementById('marker');if(!id||(zones[id]||[]).length===0){marker.style.display='none';return}const box=new THREE.Box3();zones[id].forEach(m=>box.expandByObject(m));const c=box.getCenter(new THREE.Vector3()).project(camera);const r=app.getBoundingClientRect();marker.style.left=((c.x*.5+.5)*r.width)+'px';marker.style.top=((-c.y*.5+.5)*r.height)+'px';marker.innerHTML=`<strong>${friendly(id)}</strong><small>${MODEL_NAMES[activeModel]}</small><b>${price(id).toLocaleString('ru-RU')} ₽</b>`;marker.style.display='block'}
function recalc(){total=0;for(const [id,ms] of Object.entries(zones))if(ms.some(m=>states[activeModel].get(m.uuid)?.hex))total+=price(id);document.getElementById('total').textContent=total.toLocaleString('ru-RU')+' ₽'}
function renderParts(){const box=document.getElementById('parts');box.innerHTML='';const painted=Object.keys(zoneDefs).filter(id=>(zones[id]||[]).some(m=>states[activeModel].get(m.uuid)?.hex));if(!painted.length){box.innerHTML='<div class="empty">Пока ничего не выбрано</div>';return}painted.forEach(id=>{const b=document.createElement('button');b.className='part'+(selectedZone===id?' active':'');b.innerHTML=`<span><span class="name">${friendly(id)}</span><span class="meta">${MODEL_NAMES[activeModel]}</span></span><span class="price">${price(id).toLocaleString('ru-RU')} ₽</span>`;b.onclick=()=>selectZone(id);box.appendChild(b)})}
function rebuildZoneUI(){const box=document.getElementById('zones');box.innerHTML='';for(const id of Object.keys(zoneDefs)){if(!(zones[id]||[]).length)continue;const b=document.createElement('button');b.className='zone';b.innerHTML=`${friendly(id)}<small>${price(id).toLocaleString('ru-RU')} ₽</small>`;b.onclick=()=>{selectZone(id);if(tool!=='select')paintZone(id)};box.appendChild(b)} }
function buildZones(root,model){Object.keys(zones).forEach(k=>delete zones[k]);const map=new Map();root.traverse(o=>{if(o.isMesh){smoothMesh(o);map.set(o.name,o)}});if(model==='dodge'){for(const [id,names] of Object.entries(dodgeMap))zones[id]=names.map(n=>map.get(n)).filter(Boolean);zones.mirrorL=[];zones.mirrorR=[]}else{for(const id of Object.keys(zoneDefs))zones[id]=[];const frontDoorL=/^MBPanel_(030|031|034)_/;const frontDoorR=/^MBPanel_(037|038|041)_/;const rearDoorL=/^MBPanel_(032|036|076|077|079|080|081|083|095|096|097|098|099|100|101)_/;const rearDoorR=/^MBPanel_(039|043|113|114|115|116|117|118|119|120|121|123|124|125|127)_/;root.traverse(o=>{if(!o.isMesh)return;let zone=null;if(o.name==='MBPanel_010_trunk')zone='quarterL';else if(o.name==='MBPanel_017_trunk')zone='quarterR';else if(rearDoorL.test(o.name))zone='doorRearL';else if(rearDoorR.test(o.name))zone='doorRearR';else if(frontDoorL.test(o.name))zone='doorFrontL';else if(frontDoorR.test(o.name))zone='doorFrontR';else{const m=o.name.match(/_((?:hood|roof|fenderFrontL|fenderFrontR|doorFrontL|doorFrontR|doorRearL|doorRearR|quarterL|quarterR|trunk|bumperFront|bumperRear|sideLowerL|sideLowerR|mirrorL|mirrorR))$/);if(m)zone=m[1]}if(zone)zones[zone].push(o)})}rebuildZoneUI();selectedZone=null;document.getElementById('selectedInfo').textContent='Нажмите на деталь автомобиля';renderParts()}
function coverMercedesPlate(root){root.traverse(o=>{if(!o.isMesh)return;if(o.name!=='Object_6'&&o.material?.name!=='metal_white')return;o.material=new THREE.MeshPhysicalMaterial({color:0x111111,roughness:.45,metalness:.15,envMapIntensity:.6})})}
function onModelReady(model,r){ensureEnv();r.scale.setScalar(model==='dodge'?1.25:1.45);r.position.y=.03;scene.add(r);roots[model]=r;Object.values(roots).forEach(x=>x.visible=false);r.visible=true;buildZones(r,model);if(model==='mercedes')coverMercedesPlate(r);document.getElementById('status').textContent=MODEL_NAMES[model]+' готов'}
function loadModel(model){activeModel=model;document.querySelectorAll('[data-model]').forEach(b=>b.classList.toggle('active',b.dataset.model===model));if(roots[model]){Object.values(roots).forEach(r=>r.visible=false);roots[model].visible=true;controls.target.set(0,.7,0);selectedZone=null;buildZones(roots[model],model);if(model==='mercedes')coverMercedesPlate(roots[model]);document.getElementById('status').textContent=MODEL_NAMES[model]+' готов';return}document.getElementById('status').textContent='Загрузка '+MODEL_NAMES[model];const cached=window.__wrapGlb?.[model];if(cached){loader.parse(cached,'',g=>onModelReady(model,g.scene),()=>document.getElementById('status').textContent='Ошибка загрузки '+MODEL_NAMES[model]);return}loader.load(MODEL_URLS[model],g=>onModelReady(model,g.scene),xhr=>{if(xhr.total)document.getElementById('status').textContent='Загрузка '+MODEL_NAMES[model]+' '+Math.round(xhr.loaded/xhr.total*100)+'%'},()=>document.getElementById('status').textContent='Ошибка загрузки '+MODEL_NAMES[model])}
for(const [hex,n] of colors){const b=document.createElement('button');b.className='swatch';b.style.background=hex;b.title=n;b.dataset.hex=hex;b.onclick=()=>{activeHex=hex;document.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('active',x===b));if(selectedZone){const old=tool;if(tool==='select')tool='fill';paintZone(selectedZone);tool=old}};document.getElementById('swatches').appendChild(b)}document.querySelector('.swatch[data-hex="#d71935"]').classList.add('active');
document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{if(b.dataset.model==='mercedes')prefetchMercedesModel();loadModel(b.dataset.model)});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b))});
document.querySelectorAll('[data-finish]').forEach(b=>b.onclick=()=>{finish=b.dataset.finish;document.querySelectorAll('[data-finish]').forEach(x=>x.classList.toggle('active',x===b));if(selectedZone){const old=tool;if(tool==='select')tool='fill';paintZone(selectedZone);tool=old}});
document.querySelectorAll('[data-effect]').forEach(b=>b.onclick=()=>{effect=b.dataset.effect;document.querySelectorAll('[data-effect]').forEach(x=>x.classList.toggle('active',x===b));if(selectedZone){const old=tool;if(tool==='select')tool='fill';paintZone(selectedZone);tool=old}});
renderer.domElement.addEventListener('pointerdown',e=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const all=Object.values(zones).flat().filter(Boolean);const hits=ray.intersectObjects(all,true);if(!hits.length)return;let hit=hits[0].object,found=null;for(const [id,ms] of Object.entries(zones))if(ms.includes(hit)){found=id;break}if(found){selectZone(found);if(tool!=='select')paintZone(found)}});
document.getElementById('rotate').onclick=()=>{rotating=!rotating;document.getElementById('rotate').classList.toggle('active',rotating)};
document.getElementById('reset').onclick=()=>{camera.position.set(4.8,2.2,6.2);controls.target.set(0,.7,0);controls.update();if(roots[activeModel])roots[activeModel].rotation.set(0,0,0)};
document.getElementById('quote').onclick=()=>alert(`Подбор сформирован для ${MODEL_NAMES[activeModel]}. Здесь можно подключить CRM/Telegram/форму заявки.`);
function resize(){const r=app.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function loop(){requestAnimationFrame(loop);if(rotating&&roots[activeModel])roots[activeModel].rotateY(.0018);controls.update();renderer.render(scene,camera);if(selectedZone)markerFor(selectedZone)}loop();
MeshoptDecoder.ready.then(()=>{loader.setMeshoptDecoder(MeshoptDecoder);loadModel('dodge')});
